name: Validate code format with goimports
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1

    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Check diff
      run: |
        if $(go env GOPATH)/bin/goimports -d . | grep . ; then
          exit 1
        fi

