name: Check prerequisites
on: [push, pull_request]
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'

    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Check formatting with goimports
      run: |
        if $(go env GOPATH)/bin/goimports -d . | grep . ; then
          exit 1
        fi

  go-vet:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Diagnose the code with go vet
      run: go vet ./...

